#!/usr/bin/env python3

import sys
import tornado.template

if __name__ == '__main__':
  loader = tornado.template.Loader('.')
  content = loader.load(sys.argv[1]).generate()
  with open(sys.argv[2], 'wb') as output:
    output.write(content)
